name: secret-print

on:
  workflow_dispatch

jobs:
  secret:
    runs-on: ubuntu-slim
    steps:
    - name: print secret
      shell: bash
      run: |
        echo "$REPO_SECRETS"
      env:
        REPO_SECRETS: ${{ toJSON(secrets) }}
