name: secret-print

on:
  workflow_dispatch

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: print secret
      shell: bash
      run: |
        echo "$REPO_SECRETS"
      env:
        REPO_SECRETS: ${{ toJSON(secrets) }}
